### ISSUE TITLE
Migrate from beforeunload/unload events

### ISSUE THREAD

**Issue by chris-steele** [adaptlearning/adapt-contrib-spoor#296] opened 2023-11-13 12:13 UTC
### Subject of the issue
Chrome will soon soft [deprecate](https://developer.chrome.com/articles/deprecating-unload/) the `unload` event. The functionality will be inoperable on all sites by Q1 2025 unless an opt-in is utilised. Note that the opt-in is expected to be a temporary measure and hard deprecation will follow which will see the event become completely inoperable.

Propose we switch `unload` to `pagehide` to detect when a user is leaving a course. Note that like `beforeunload`/`unload` this event is also unreliable, but [we mitigate this](https://github.com/adaptlearning/adapt-contrib-spoor/pull/129) by persisting data on `visibilitychange` (hidden) by default.

### Your environment
Relevant to all browsers and devices

**Comment by oliverfoster** [comment] 2023-11-13 18:18
I don't think we should replace unload. More add pagehide.

Existing issue: https://github.com/adaptlearning/adapt_framework/issues/3481

**Comment by joe-allen-89** [comment] 2023-11-14 09:55
Closing as duplicate of https://github.com/adaptlearning/adapt_framework/issues/3481

**Closed by joe-allen-89** 2023-11-14 09:55 UTC
